---

- name: Set Plugin Info
  set_fact:
    plugin_name: 'redmine_wiki_extensions'
    plugin_version: '0.7.0'
    plugin_url: 'https://bitbucket.org/haru_iida/redmine_wiki_extensions/downloads'

- name: プラグイン名
  debug: msg={{ plugin_name }}

- name: ソースをダウンロード
  get_url:
    url={{ plugin_url }}/{{ plugin_name }}-{{ plugin_version }}.zip
    dest=/usr/local/src/{{ plugin_name }}-{{ plugin_version }}.zip

- name: ソースを展開
  sudo_user: "{{ redmine_user.name }}"
  unarchive:
    src=/usr/local/src/{{ plugin_name }}-{{ plugin_version }}.zip
    dest=/opt/redmines/redmine/plugins
    copy=no
    creates=/opt/redmines/redmine/plugins/{{ plugin_name }}/README.rdoc

