---

- name: Set Plugin Info
  set_fact:
    plugin_name: 'redmine_absolute_dates'
    plugin_version: '0.0.2'
    plugin_url: 'https://github.com/suer/redmine_absolute_dates/archive'

- name: プラグイン名
  debug: msg={{ plugin_name }}

- name: ソースをダウンロード
  get_url:
    url={{ plugin_url }}/{{ plugin_version }}.zip
    dest=/usr/local/src/{{ plugin_name }}-{{ plugin_version }}.zip

- name: ソースを展開
  sudo_user: "{{ redmine_user.name }}"
  unarchive:
    src=/usr/local/src/{{ plugin_name }}-{{ plugin_version }}.zip
    dest=/opt/redmines/redmine/plugins
    copy=no
    creates=/opt/redmines/redmine/plugins/{{ plugin_name }}/README.rdoc

- name: フォルダ名リネーム
  command: mv {{ plugin_name }}-{{ plugin_version }} {{ plugin_name }}
  args:
    chdir:   /opt/redmines/redmine/plugins/
    creates: /opt/redmines/redmine/plugins/{{ plugin_name }}/README.rdoc

