---
# This playbook deploys the whole application stack in this site.

# 共通設定を全ホストに対して実行
- hosts: all
  sudo: yes
  roles:
  - common

# redmineサーバを設定
- hosts: redmine-server
  sudo: yes
  vars:
    ruby_version: 2.2.2
    rbenv_user:
      name: redmine
      groups: sudo
      password: $1$SomeSalt$vLNQt/gk1af5Cbgrx38Gx/ #ハッシュ化パスワード:redmine
      login_shell: /bin/bash
  roles:
  - mysql
  - redmine

